export default [
  {
    id: "zh3",
    name: "字魂3号-英雄黑体",
    fontName: "zihun3hao\\-yingxiongheiti",
    image: "/images/fonts/zh3.svg",
  },
  {
    id: "zh27",
    name: "字魂27号-布丁体",
    fontName: "zihun27hao\\-budingti",
    image: "/images/fonts/zh27.svg",
  },
  {
    id: "zh35",
    name: "字魂35号-经典黑体",
    fontName: "zihun35hao\\-jingdianheiti",
    image: "/images/fonts/zh35.svg",
  },
  {
    id: "zh45",
    name: "字魂45号-冰宇雅宋",
    fontName: "zihun45hao\\-bingyuyasong",
    image: "/images/fonts/zh45.svg",
  },
  {
    id: "zh59",
    name: "字魂59号-创粗黑",
    fontName: "zihun59hao\\-chuangcuhei",
    image: "/images/fonts/zh59.svg",
  },
  {
    id: "zh78",
    name: "字魂78号-空灵体",
    fontName: "zihun78hao\\-konglignti",
    image: "/images/fonts/zh78.svg",
  },
  {
    id: "zh141",
    name: "字魂141号-活力悦动体",
    fontName: "zihun141hao\\-huoliyuedongti",
    image: "/images/fonts/zh141.svg",
  },
  {
    id: "zh167",
    name: "字魂167号-活力悦动体",
    fontName: "zihun167hao\\-yirenhei",
    image: "/images/fonts/zh167.svg",
  },
  {
    id: "zh195",
    name: "字魂195号-萌趣百奇体",
    fontName: "zihun195hao\\-mengqubaiqiti",
    image: "/images/fonts/zh195.svg",
  },
  {
    id: "zh199",
    name: "字魂199号-萌趣脆脆体",
    fontName: "zihun199hao\\-mengqucuicuiti",
    image: "/images/fonts/zh199.svg",
  },
  {
    id: "zh207",
    name: "字魂207号-铁甲智能黑",
    fontName: "zihun207hao\\-tiejiazhinenghei",
    image: "/images/fonts/zh207.svg",
  },
  {
    id: "zh238",
    name: "字魂238号-铁甲智能黑",
    fontName: "zihun238hao\\-tiejiazhinenghei",
    image: "/images/fonts/zh238.svg",
  },
  {
    id: "zh252",
    name: "字魂252号-凤仪手书",
    fontName: "zihun252hao\\-fengyishoushu",
    image: "/images/fonts/zh252.svg",
  },
];
